#!/usr/bin/env python3
"""
build_index.py — KB index auto-builder.

Scans kb/*.md, anonymization/*.py, and root reference files, then writes
kb/INDEX.md with a manifest of every file, its purpose, size, and
last-modified date.

Run from Tools/:
  python kb/build_index.py
Or from kb/:
  python build_index.py
"""

import ast
import datetime
import pathlib
import re

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BASE_DIR = pathlib.Path(__file__).parent.parent   # Tools/
KB_DIR   = BASE_DIR / "kb"
ANON_DIR = BASE_DIR / "anonymization"
INDEX_PATH = KB_DIR / "INDEX.md"

ROOT_REF_NAMES = ["CONTRACT-RULES.md", "CLAUDE.md", "NEAR_TERM_ENHANCEMENTS.md"]

# ---------------------------------------------------------------------------
# Purpose extraction
# ---------------------------------------------------------------------------

def first_md_heading(path: pathlib.Path) -> str:
    """Return text of first # / ## / ### heading, or stem if none found."""
    for line in path.read_text(encoding='utf-8', errors='replace').splitlines():
        m = re.match(r'^#{1,3}\s+(.+)', line)
        if m:
            return m.group(1).strip()
    return path.stem


def first_py_purpose(path: pathlib.Path) -> str:
    """Return first non-empty line of the module docstring, or stem if absent."""
    src = path.read_text(encoding='utf-8', errors='replace')
    try:
        tree = ast.parse(src)
        docstring = ast.get_docstring(tree)
        if docstring:
            for line in docstring.splitlines():
                stripped = line.strip()
                if stripped:
                    return stripped
    except SyntaxError:
        pass
    # Fallback: first non-shebang #-comment
    for line in src.splitlines():
        stripped = line.strip()
        if stripped.startswith('#') and not stripped.startswith('#!/'):
            return stripped.lstrip('#').strip()
    return path.stem

# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _file_row(path: pathlib.Path, purpose: str) -> str:
    stat   = path.stat()
    size   = f"{stat.st_size / 1024:.1f} KB"
    mtime  = datetime.datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M')
    return f"| `{path.name}` | {purpose} | {size} | {mtime} |"


def _section(title: str, files: list[pathlib.Path], purpose_fn) -> str:
    rows = [
        f"## {title}",
        "",
        "| File | Purpose | Size | Last Modified |",
        "|------|---------|------|---------------|",
    ]
    for f in files:
        rows.append(_file_row(f, purpose_fn(f)))
    return "\n".join(rows)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')

    kb_mds   = sorted(f for f in KB_DIR.glob("*.md") if f.name != "INDEX.md")
    anon_pys = sorted(ANON_DIR.glob("*.py"))
    root_refs = [BASE_DIR / n for n in ROOT_REF_NAMES if (BASE_DIR / n).exists()]

    content = "\n".join([
        "# Knowledge Base Index",
        "",
        f"Auto-generated {timestamp} by `build_index.py`.",
        f"Files: {len(kb_mds)} KB docs · {len(anon_pys)} pipeline scripts · {len(root_refs)} root refs",
        "",
        "---",
        "",
        _section("Reference Files",      kb_mds,   first_md_heading),
        "",
        "---",
        "",
        _section("Pipeline Scripts",     anon_pys, first_py_purpose),
        "",
        "---",
        "",
        _section("Root Reference Files", root_refs, first_md_heading),
        "",
        "---",
        "",
        "_Auto-generated by build_index.py — do not edit manually._",
        "",
    ])

    INDEX_PATH.write_text(content, encoding='utf-8')
    print(content)
    print(f"[build_index] Wrote {INDEX_PATH}")
    print(f"[build_index] Sections: Reference Files ({len(kb_mds)}), "
          f"Pipeline Scripts ({len(anon_pys)}), Root Reference Files ({len(root_refs)})")


if __name__ == '__main__':
    main()
